# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/vision-cad',
                'doc_host': 'https://Ramon-PR.github.io',
                'git_url': 'https://github.com/Ramon-PR/vision-cad',
                'lib_path': 'vision_cad'},
  'syms': {}}
