# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_camera.ipynb.

# %% auto #0
__all__ = ['set_cam_format_fourcc', 'get_cam_format_fourcc', 'set_cam_resolution', 'get_cam_resolution', 'test_camera_feed']

# %% ../nbs/00_camera.ipynb #aaf95620
import cv2
import time


# %% ../nbs/00_camera.ipynb #8678f27b
def set_cam_format_fourcc(cam, format='MJPG'):
    "Set Pixel or Compression format"
    # Options include 'MJPG', 'YUYV', 'RGB3', etc. Check your camera documentation for supported formats.
    # Check that the format is valid, otherwise return an error message
    valid_formats = ['MJPG', 'YUYV', 'RGB3', 'GRAY', 'YUV420P', 'NV12', 'NV21']
    if format not in valid_formats:
        raise ValueError(f"Invalid format '{format}'. Valid formats are: {valid_formats}")

    # Set the camera to output raw frames (uncompressed)
    cam.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*format))

def get_cam_format_fourcc(cam):
    "Get the current Pixel or Compression format"
    codec_int = int(cam.get(cv2.CAP_PROP_FOURCC))
    codec_str = "".join([chr((codec_int >> 8 * i) & 0xFF) for i in range(4)])
    return codec_str


# %% ../nbs/00_camera.ipynb #9782f74c
def set_cam_resolution(cam, width=640, height=480):
    "Set the resolution of the camera feed"
    cam.set(cv2.CAP_PROP_FRAME_WIDTH, width)
    cam.set(cv2.CAP_PROP_FRAME_HEIGHT, height)

def get_cam_resolution(cam):
    "Get the current resolution of the camera feed"
    width = int(cam.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cam.get(cv2.CAP_PROP_FRAME_HEIGHT))
    return width, height

# %% ../nbs/00_camera.ipynb #6a29d165
def test_camera_feed(camera_id=0, format='MJPG', width=640, height=480):
    cap = cv2.VideoCapture(camera_id)
    set_cam_format_fourcc(cap, format)
    set_cam_resolution(cap, width, height)

    if not cap.isOpened():
        print("Cannot open camera")
        return

    print(f"Camera format: {get_cam_format_fourcc(cap)}")
    print(f"Camera resolution: {get_cam_resolution(cap)}")

    print("Press 'q' to quit")


    prev_frame_time = 0
    new_frame_time = 0

    while cap.isOpened():
        ret, frame = cap.read()

        if not ret:
            # If it fails, print the specific error
            print("Failed to grab frame")
            break

        # Calculate FPS
        new_frame_time = time.time()
        fps = 1 / (new_frame_time - prev_frame_time)
        prev_frame_time = new_frame_time
        
        # Format and draw the FPS on the frame
        fps_text = f"FPS: {int(fps)}"
        cv2.putText(frame, fps_text, (20, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)    
        
        cv2.imshow('Live Camera', frame)
        
        # Use Esc or 'q' to exit the loop
        if cv2.waitKey(1) & 0xFF in [27, ord('q')]:  # Esc key or 'q'
            print("Exiting...")
            break

    cap.release()
    cv2.destroyAllWindows()
