# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_camera.ipynb.

# %% auto #0
__all__ = ['camera_id', 'cap']

# %% ../nbs/00_camera.ipynb #646cafec
import cv2


# %% ../nbs/00_camera.ipynb #0f8b1d55
camera_id = 0 # or an url for an IP camera "192.168.1.100:8080/video"
cap = cv2.VideoCapture(camera_id)


# %% ../nbs/00_camera.ipynb #1984aec8
if not cap.isOpened():
    raise Exception("Could not open video device")

# Set frame size (optional)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

# %% ../nbs/00_camera.ipynb #382c8775
print("Press 'q' to quit")

while True:
    ret, frame = cap.read()
    if not ret:
        print("Failed to grab frame")
        break
    
    # Display the frame
    cv2.imshow('Live Camera', frame)
    
    # Exit when 'q' is pressed
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Release resources
cap.release()
cv2.destroyAllWindows()
